language: ruby
rvm:
  - 2.7.0
sudo: false
script: bundle exec rake deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: gh-pages